[tool.poetry]
name = "university-practical-exam"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT OR Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.4"
django-livereload-server = "^0.3.2"
django-pgtrigger = "^2.3.2"
django-widget-tweaks = "^1.4.8"
numpy = "^1.20.3"
psycopg2 = "^2.8.6"
pygad = "^2.14.3"

[tool.poetry.dev-dependencies]
black = {version = "^21.6b0", allow-prereleases = true}
mypy = {version = "^0.902", allow-prereleases = true}
django-stubs = {version = "^1.8.0", allow-prereleases = true}
types-python-dateutil = {version = "^0.1.3", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
